name: CI

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./site

jobs:
  build:
    strategy:
      matrix:
        node-version: [22.13.0]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './site/package-lock.json'
      - run: npm ci
      - run: npm run test
      - run: npm run build
